server:
  port: 8084
spring:
  application:
    name: "enrollment-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/enrollments
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/athenaRealm
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

services.user.url: "http://localhost:8088"
