server:
  port: 8088
  shutdown: graceful

spring:
  application:
    name: "user-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/athenaRealm
          jwk-set-uri: http://localhost:8080/realms/athenaRealm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

keycloak:
  server-url: http://localhost:8080
  realm: athenaRealm
  client-id: edge-service
  client-secret: akf3zJQ0sikPt0XqzMOKA37FsQQqMCJP

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
